/**
 * @typedef {import('./types').AVOIDANCE_RULES} AVOIDANCE_RULES
 */

/** @type {AVOIDANCE_RULES} */
export const AVOIDANCE_RULES = {
    NONE: 'NONE',
    AVOID_CONSECUTIVE_ROLES: 'AVOID_CONSECUTIVE_ROLES',
    AVOID_CONSECUTIVE_SHIFTS: 'AVOID_CONSECUTIVE_SHIFTS',
    AVOID_DUPLICATE_SHIFTS: 'AVOID_DUPLICATE_SHIFTS',
};